### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by simnalamburt** [simnalamburt/snucse.malloclab#1]
- [x] `free()` 구현
- [x] 블럭 쪼개기
  - [x] 쪼갠 직후 오른쪽 코얼레싱 시도
- coalescing
  - [x] left
  - [x] right
- `realloc()` 구현
  - [x] 작아지는 realloc의 경우 스플릿
    - [x] 쪼갠 직후 오른쪽 코얼레싱 시도
  - 커지는 realloc의 경우 코얼레싱 시도
    - [x] 오른쪽으로 코얼레싱
    - [x] 안되면 왼쪽으로 코얼레싱
    - [x] 코얼레싱할때마다 크기에 맞게 스플릿 시도
      1. 무조건 왼쪽으로 코얼레싱 하고 보기
      2. 필요할때만 왼쪽으로 코얼레싱하기
- ~~유틸라이제이션 높이기~~ 그만둠
- ~~`sbrk()` 뭉텅이로 호출하기~~ 이미 스루풋이 만점이라 안그러기로함
